<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAucmRiNgFWjm8+v4LNolM'."\n".'BOT2OYq7g/w6lzHlxnT8CRE1+nEzgkFLFT3xIL1d6d1WJbPSLG56iaAfzn/fNJlj'."\n".'cc8/va/DgkqAFakFg3hYCyVrDGgvCao7aonzNuXdj3zOuEXaUGitcZjPzxbkYy7s'."\n".'xViO6lXZiumSu2xX9ANRxYfHcOdJPBGi6qimlflGzIs/3dS2GSX7aQpMhrmto+hf'."\n".'yC3Dl12D3eN04ylmygWNUlb/8eYHwpn7TEkzkArIwKiQKVzlBHKXn+N3wcT4hGbR'."\n".'avBoRElELdHSx6WYJG0VFC27369+GsVIUXh363sbHLokxT4zVvIBUvwrvYhPgdlD'."\n".'nQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
