<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRoyDn9K\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRoyDn9K/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRoyDn9K.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRoyDn9K\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerRoyDn9K\appAppKernelDevDebugContainer([
    'container.build_hash' => 'RoyDn9K',
    'container.build_id' => '85b50be4',
    'container.build_time' => 1710500444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRoyDn9K');
