<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWVpxmCu\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWVpxmCu/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWVpxmCu.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWVpxmCu\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerWVpxmCu\appAppKernelDevDebugContainer([
    'container.build_hash' => 'WVpxmCu',
    'container.build_id' => '9dff3ffd',
    'container.build_time' => 1710515540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWVpxmCu');
